### ISSUE TITLE
InvalidPath and NP exceptions when enabling MP language server

### ISSUE THREAD

**Issue by bensonnw** [MicroShed/microprofile-language-server#2]
- [ ] Could not find a root workspace folder: java.nio.file.InvalidPathException

- [ ] org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer fireError
SEVERE: An error occurred while processing an incoming message.
java.lang.NullPointerException
at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:279)
at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:19

**Comment by ericglau** [comment]
Fixed by https://github.com/MicroShed/microprofile-language-server/pull/5
